### ISSUE TITLE
Config project

### ISSUE THREAD

**Issue by duythanh7903** [Wrxhard/YoutubeToMp3Converter#1]
Anh ơi, anh có thể chỉ cho em cách chi tiết config dự án được không ạ, em có thử config python các thứ nhưng mà không chạy được

**Comment by Wrxhard** [comment]
Bạn config chaquopy chưa

**Comment by Wrxhard** [comment]
Official docs: https://chaquo.com/chaquopy/doc/current/android.html
Video tham khảo: https://www.youtube.com/watch?v=dFtxLCSu3wQ

**Comment by Wrxhard** [comment]
À với bạn sử dụng python 3.8 để được hỗ trợ đầy đủ nhé các python version cao hơn có thể không hỗ trợ đầy đủ các thư viện

**Comment by duythanh7903** [comment]
vâng em cảm ơn ạ
